# Generated by Django 5.2.17 on 2026-09-24 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('queue_id', models.PositiveIntegerField(db_index=True)),
                ('game_mode', models.CharField(max_length=32)),
                ('game_start', models.DateTimeField(db_index=True)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-game_start',),
            },
        ),
        migrations.CreateModel(
            name='RiotAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=128, unique=True)),
                ('game_name', models.CharField(max_length=32)),
                ('tag_line', models.CharField(max_length=8)),
                ('platform_region', models.CharField(default='na1', max_length=8)),
                ('routing_region', models.CharField(default='americas', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('game_name', 'tag_line'),
                'constraints': [models.UniqueConstraint(fields=('game_name', 'tag_line', 'routing_region'), name='unique_riot_id_per_routing_region')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=128)),
                ('game_name', models.CharField(blank=True, max_length=32)),
                ('tag_line', models.CharField(blank=True, max_length=8)),
                ('summoner_name', models.CharField(blank=True, max_length=64)),
                ('win', models.BooleanField()),
                ('damage_per_minute', models.FloatField()),
                ('total_damage_to_champions', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='stats.match')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='stats.riotaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['puuid', 'match'], name='stats_parti_puuid_a659d7_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'puuid'), name='unique_participant_per_match')],
            },
        ),
    ]
