# Generated by Django 6.1.1 on 2026-09-25 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_applicationsecret'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisQueueGuard',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('event_version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=240)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('processed_by', models.CharField(max_length=80)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event_id', 'processed_by'), name='unique_processed_event')],
            },
        ),
        migrations.CreateModel(
            name='PublicRateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_hash', models.CharField(max_length=64)),
                ('window_seconds', models.PositiveIntegerField()),
                ('window_started_at', models.DateTimeField()),
                ('request_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor_hash', 'window_seconds'), name='unique_public_rate_limit_bucket')],
            },
        ),
        migrations.CreateModel(
            name='RiotRateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_region', models.CharField(max_length=16)),
                ('window_seconds', models.PositiveIntegerField()),
                ('window_started_at', models.DateTimeField()),
                ('request_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('routing_region', 'window_seconds'), name='unique_riot_rate_limit_bucket')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=32)),
                ('tag_line', models.CharField(max_length=8)),
                ('normalized_game_name', models.CharField(editable=False, max_length=32)),
                ('normalized_tag_line', models.CharField(editable=False, max_length=8)),
                ('platform_region', models.CharField(default='na1', max_length=8)),
                ('routing_region', models.CharField(default='americas', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('requester_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('public_message', models.CharField(blank=True, max_length=240)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_requests', to='stats.riotaccount')),
            ],
            options={
                'ordering': ('-requested_at',),
                'indexes': [models.Index(fields=['normalized_game_name', 'normalized_tag_line', 'routing_region'], name='analysis_request_riot_id_idx')],
            },
        ),
    ]
